import { afterEach, describe, expect, it, vi } from "vitest"
import { createController, type Controller } from "../src/controller.ts"
import { parseOptions } from "../src/options.ts"
import { fixture, session } from "./fixture.ts"

let controller: Controller | undefined
afterEach(() => { controller?.dispose(); controller = undefined; vi.useRealTimers() })
function setup(initial = [session("root")], options = {}) {
  const f = fixture(initial)
  controller = createController(f.context, parseOptions(options))
  return { ...f, c: controller }
}

describe("agents view lifecycle", () => {
  it("inherits the live prompt model and variant instead of stale session metadata", async () => {
    const f = setup([session("other", { location: { directory: "/other" }, model: { providerID: "acme", id: "old" } })])
    await f.c.refresh()
    f.setRoute({ type: "session", sessionID: "other" })
    vi.spyOn(f.context.ui.model, "current").mockReturnValue({ providerID: "acme", modelID: "new", variant: "high" })
    await f.c.open()
    expect(f.c.memory.model).toEqual({ providerID: "acme", id: "new", variant: "high" })
    await f.c.dispatch("use my selected model")
    expect(f.create.mock.calls[0][0]).toMatchObject({ location: { directory: "/other" }, model: { providerID: "acme", id: "new", variant: "high" } })
  })
  it("does not carry a different conversation's model into one using defaults", async () => {
    const f = setup([session("defaults")])
    await f.c.refresh()
    f.c.updateMemory((draft) => { draft.model = { providerID: "old", id: "unavailable" } })
    f.setRoute({ type: "session", sessionID: "defaults" })
    await f.c.open()
    expect(f.c.memory.model).toBeNull()
    await f.c.dispatch("use defaults")
    expect(f.create.mock.calls[0][0].model).toBeUndefined()
  })
  it("adopts folder-first grouping for older preferences and remembers an explicit toggle", async () => {
    const f = fixture()
    f.stores.set("preferences", { grouping: "state", pinned: ["root"], hidden: [], defaultToAgentsView: true })
    controller = createController(f.context, parseOptions({}))
    expect(controller.grouping()).toBe("directory")
    await controller.toggleGrouping()
    expect(controller.grouping()).toBe("state")
    expect(controller.preferences.pinned).toEqual(["root"])
    controller.dispose()
    controller = createController(f.context, parseOptions({}))
    expect(controller.grouping()).toBe("state")
  })
  it("detaches a running session without interrupting and Esc returns to the route snapshot", () => {
    const f = setup()
    f.setRoute({ type: "session", sessionID: "root" })
    f.c.open()
    expect(f.route()).toMatchObject({ type: "plugin", name: "agents-view" })
    expect(f.c.memory.selected).toBe("root")
    expect(f.interrupt).not.toHaveBeenCalled()
    f.c.attach("other")
    f.c.back()
    expect(f.route()).toEqual({ type: "session", sessionID: "root" })
  })
  it("dispatches an independent root session and keeps the table open", async () => {
    const f = setup()
    f.c.open()
    f.c.updateMemory((draft) => { draft.draft = "fix login"; draft.agent = "reviewer"; draft.model = { providerID: "acme", id: "model" } })
    expect(await f.c.dispatch("fix login")).toBe(true)
    expect(f.create).toHaveBeenCalledWith(expect.objectContaining({ agent: "reviewer", model: { providerID: "acme", id: "model" }, location: { directory: "/project" } }), expect.anything())
    expect(f.create.mock.calls[0][0]).not.toHaveProperty("parentID")
    expect(f.prompt).toHaveBeenCalledWith({ sessionID: "created", text: "fix login", delivery: "queue" }, expect.anything())
    expect(f.route().type).toBe("plugin")
    expect(f.c.memory.draft).toBe("")
  })
  it("brings a hidden originating conversation back when detaching", async () => {
    const f = setup()
    await f.c.refresh()
    await f.c.stopOrHide("root", 1000)
    await f.c.stopOrHide("root", 2000)
    expect(f.c.rows()).toHaveLength(0)
    f.setRoute({ type: "session", sessionID: "root" })
    await f.c.open()
    expect(f.c.rows().map((row) => row.session.id)).toEqual(["root"])
    expect(f.c.memory.selected).toBe("root")
    expect(f.c.memory.previous).toEqual({ type: "session", sessionID: "root" })
    expect(f.interrupt).toHaveBeenCalledOnce()
  })
  it("reloads live-root output on refresh even when inventory timestamps are unchanged", async () => {
    const f = setup([session("root"), session("child", { parentID: "root" }), session("finished", { outcome: "succeeded" })])
    vi.mocked(f.context.client.session.active).mockResolvedValue({ child: { type: "running" } })
    const messages = vi.mocked(f.context.client.message.list)
    messages.mockImplementation(async ({ sessionID }) => ({ data: [{
      id: sessionID, type: "user", time: { created: 1 }, text: "First output",
    }], cursor: {} }))
    await f.c.refresh()
    await f.c.loadPreviews(f.c.rows().map((row) => row.session))
    expect(f.c.rows().find((row) => row.session.id === "root")?.summary).toBe("First output")
    messages.mockImplementation(async ({ sessionID }) => ({ data: [{
      id: sessionID, type: "user", time: { created: 1 }, text: "New progress",
    }], cursor: {} }))
    await f.c.refresh()
    await f.c.loadPreviews(f.c.rows().map((row) => row.session))
    expect(f.c.rows().find((row) => row.session.id === "root")?.summary).toBe("New progress")
    expect(f.c.rows().find((row) => row.session.id === "finished")?.summary).toBe("First output")
    expect(messages).toHaveBeenCalledTimes(3)
  })
  it("attaches only after successful prompt admission", async () => {
    const f = setup()
    await f.c.dispatch("fix login", true)
    expect(f.route()).toEqual({ type: "session", sessionID: "created" })
  })
  it("preserves a failed prompt draft and its recoverable session", async () => {
    const f = setup()
    f.prompt.mockRejectedValue(new Error("Disconnected"))
    f.c.updateMemory((draft) => { draft.draft = "keep me" })
    expect(await f.c.dispatch("keep me", true)).toBe(false)
    expect(f.c.memory.draft).toBe("keep me")
    expect(f.c.rows().some((row) => row.session.id === "created")).toBe(true)
    expect(f.remove).not.toHaveBeenCalled()
    expect(f.route().type).toBe("home")
  })
  it("queues a peek reply without navigating or creating another session", async () => {
    const f = setup()
    f.c.updateMemory((draft) => { draft.replies.root = "continue" })
    await f.c.reply("root", "continue")
    expect(f.prompt).toHaveBeenCalledWith({ sessionID: "root", text: "continue", delivery: "queue" }, expect.anything())
    expect(f.create).not.toHaveBeenCalled()
    expect(f.navigate).not.toHaveBeenCalled()
    expect(f.c.memory.replies.root).toBeUndefined()
  })
  it("keeps edits made while prompt admission is in flight", async () => {
    const f = setup()
    f.c.updateMemory((draft) => { draft.draft = "first task" })
    f.prompt.mockImplementation(async () => { f.c.updateMemory((draft) => { draft.draft = "next task" }) })
    await f.c.dispatch("first task")
    expect(f.c.memory.draft).toBe("next task")
  })
  it("dispatches slash commands through the command API", async () => {
    const f = setup()
    await f.c.dispatch("/review staged changes")
    expect(f.command).toHaveBeenCalledWith({ sessionID: "created", name: "review", text: "staged changes", delivery: "queue" }, expect.anything())
    expect(f.prompt).not.toHaveBeenCalled()
  })
  it("paginates and aggregates child permission requests into the root", async () => {
    const f = setup()
    f.list.mockReset().mockResolvedValueOnce({ data: [session("root")], cursor: { next: "next" } })
      .mockResolvedValueOnce({ data: [session("child", { parentID: "root" })], cursor: {} })
    vi.mocked(f.context.client.session.active).mockResolvedValue({ child: { type: "running" } })
    vi.mocked(f.context.client.permission.request.list).mockResolvedValue({ location: { directory: "/project" }, data: [{ id: "p", sessionID: "child", action: "edit", resources: ["file"] }] })
    await f.c.refresh()
    expect(f.c.rows()).toHaveLength(1)
    expect(f.c.rows()[0].state).toBe("needs-input")
    expect(f.c.rows()[0].summary).toContain("Permission: edit")
    expect(f.list.mock.calls[1][0].cursor).toBe("next")
  })
  it("filters by project identity, including worktrees", async () => {
    const f = setup([session("worktree", { location: { directory: "/trees/feature" } }), session("other", { projectID: "other" })], { scope: "project" })
    await f.c.refresh()
    expect(f.c.rows().map((row) => row.session.id)).toEqual(["worktree"])
  })
  it("dispatches into the selected directory when grouped by directory", async () => {
    const f = setup([session("worktree", { location: { directory: "/trees/feature" } })])
    await f.c.refresh()
    expect(f.c.grouping()).toBe("directory")
    f.c.updateMemory((draft) => { draft.selected = "worktree" })
    await f.c.dispatch("review this worktree")
    expect(f.create.mock.calls[0][0].location).toEqual({ directory: "/trees/feature" })
  })
  it("uses the selected conversation's directory in state grouping too", async () => {
    const f = setup([session("inactive", { outcome: "succeeded", location: { directory: "/inactive" } })])
    await f.c.refresh()
    await f.c.toggleGrouping()
    f.c.select("inactive")
    await f.c.dispatch("start a new task here")
    expect(f.create.mock.calls[0][0].location).toEqual({ directory: "/inactive" })
  })
  it("retains archived and hidden folders as dispatch targets without activating them", async () => {
    const f = setup([session("old", { location: { directory: "/inactive" }, time: { created: 1, updated: 2, archived: 3 } })])
    await f.c.refresh()
    expect(f.c.rows()).toEqual([])
    expect(f.c.directories()).toEqual(["/inactive", "/project"])
    f.c.selectDirectory("/inactive")
    expect(f.c.dispatchLocation()).toEqual({ directory: "/inactive" })
    expect(f.c.memory.selected).toBeNull()
    expect(f.context.client.location.get).toHaveBeenCalledTimes(1)
    await f.c.dispatch("restart work here")
    expect(f.create.mock.calls[0][0].location).toEqual({ directory: "/inactive" })
  })
  it("opens a blank new root session in the selected inactive folder without submitting a prompt", async () => {
    const f = setup()
    f.c.selectDirectory("/inactive")
    expect(await f.c.newSession()).toBe(true)
    expect(f.create.mock.calls[0][0].location).toEqual({ directory: "/inactive" })
    expect(f.create.mock.calls[0][0]).not.toHaveProperty("parentID")
    expect(f.prompt).not.toHaveBeenCalled()
    expect(f.route()).toEqual({ type: "session", sessionID: "created" })
    expect(f.c.memory.selectedDirectory).toBeNull()
  })
  it("preserves the chosen folder and draft if new-session creation fails", async () => {
    const f = setup()
    f.c.selectDirectory("/inactive")
    f.c.updateMemory((draft) => { draft.draft = "keep this task" })
    f.create.mockRejectedValue(new Error("Directory no longer exists"))
    expect(await f.c.newSession()).toBe(false)
    expect(f.c.dispatchLocation()).toEqual({ directory: "/inactive" })
    expect(f.c.memory.draft).toBe("keep this task")
    expect(f.navigate).not.toHaveBeenCalled()
    expect(f.c.sending()).toBe(false)
  })
  it("clears session filters and peek when choosing a folder while preserving task drafts", () => {
    const f = setup()
    f.c.updateMemory((draft) => { draft.draft = "n:old-session"; draft.peek = true })
    f.c.selectDirectory("/inactive")
    expect(f.c.memory).toMatchObject({ draft: "", peek: false, selected: null, selectedDirectory: "/inactive" })
    f.c.updateMemory((draft) => { draft.draft = "a normal task" })
    f.c.selectDirectory("/project")
    expect(f.c.memory.draft).toBe("a normal task")
  })
  it("deduplicates the launch folder and live-folder requests by Windows identity", async () => {
    const f = setup([session("root", { location: { directory: "c:\\work\\project\\" } })])
    Object.assign(f.context.location!, { directory: "C:/Work/Project" })
    vi.mocked(f.context.client.session.active).mockResolvedValue({ root: { type: "running" } })
    await f.c.refresh()
    expect(f.c.directories()).toEqual(["C:/Work/Project"])
    expect(f.c.groups()).toHaveLength(1)
    expect(f.c.groups()[0].rows).toHaveLength(1)
    expect(f.context.client.permission.request.list).toHaveBeenCalledTimes(1)
  })
  it("does not offer unrelated projects' historical folders in project scope", async () => {
    const f = setup([session("worktree", { location: { directory: "/trees/feature" } }),
      session("other", { projectID: "other", location: { directory: "/other" } })], { scope: "project" })
    await f.c.refresh()
    expect(f.c.directories()).toEqual(["/project", "/trees/feature"])
  })
  it("shows pending forms as human input without treating them as permission decisions", async () => {
    const f = setup()
    vi.mocked(f.context.client.form.list).mockResolvedValue({
      location: { directory: "/project" },
      data: [{ id: "form", sessionID: "root", title: "Question", fields: [{ type: "string", key: "answer", title: "Which database?" }] }],
    })
    await f.c.refresh()
    expect(f.c.rows()[0]).toMatchObject({ state: "needs-input", summary: "Which database?" })
  })
  it("does not load inactive historical locations that may no longer exist", async () => {
    const f = setup([session("old-worktree", { location: { directory: "/deleted/worktree" }, outcome: "succeeded" })])
    await f.c.refresh()
    expect(f.context.client.permission.request.list).toHaveBeenCalledTimes(1)
    expect(f.context.client.permission.request.list).toHaveBeenCalledWith({ location: { directory: "/project" } }, expect.anything())
  })
  it("keeps the last snapshot on network failure", async () => {
    const f = setup()
    await f.c.refresh()
    f.list.mockRejectedValue(new Error("Server offline"))
    await f.c.refresh()
    expect(f.c.rows()).toHaveLength(1)
    expect(f.c.error()).toBe("Server offline")
  })
  it("stops, then hides a row while preserving its transcript", async () => {
    const f = setup()
    await f.c.refresh()
    await f.c.stopOrHide("root", 1000)
    expect(f.c.rows()).toHaveLength(1)
    await f.c.stopOrHide("root", 2000)
    expect(f.c.rows()).toHaveLength(0)
    expect(f.remove).not.toHaveBeenCalled()
    await f.c.restoreHidden()
    expect(f.c.rows()).toHaveLength(1)
  })
  it("unsubscribes, cancels timers and aborts outstanding requests on unload", async () => {
    vi.useFakeTimers()
    const f = setup()
    await f.c.refresh()
    const signal = f.list.mock.calls[0][1].signal as AbortSignal
    f.c.dispose()
    expect(signal.aborted).toBe(true)
    expect(f.unsubscribe).toHaveBeenCalledOnce()
    await vi.advanceTimersByTimeAsync(20_000)
    expect(f.list).toHaveBeenCalledOnce()
  })
})
